# Generated by Django 4.1.6 on 2023-02-08 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_alter_task_author_alter_task_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='execute_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
