# Generated by Django 4.1.6 on 2023-02-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
