# Generated by Django 4.1.6 on 2023-02-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_taskimage_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='todo.taskcomment'),
        ),
    ]
