# Generated by Django 4.1.6 on 2023-02-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_taskcomment_task_alter_taskcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='dt_create',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='dt_update',
        ),
    ]
